name: Build YTLite IPA
on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: "URL to the decrypted IPA file"
        default: ""
        required: true
        type: string

      display_name:
        description: "App Name (Optional)"
        default: "YouTube"
        required: true
        type: string

      bundle_id:
        description: "Bundle ID (Optional)"
        default: "com.google.ios.youtube"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build YTLite IPA
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Hide Sensitive Inputs
        uses: levibostian/action-hide-sensitive-inputs@v1
        with:
          exclude_inputs: bundle_id,display_name

      - name: Download and Validate IPA
        run: |
          wget "${{ inputs.ipa_url }}" --quiet --no-verbose -O youtube.ipa
          file_type=$(file --mime-type -b youtube.ipa)
          if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
            echo "::error::Validation failed: The downloaded file is not a valid IPA. Detected type: $file_type."
            exit 1
          fi

      - name: Get YouTube Version
        run: |
          unzip -q youtube.ipa -d ytextracted
          echo "YT_VERSION=$(grep -A 1 '<key>CFBundleVersion</key>' ytextracted/Payload/YouTube.app/Info.plist | grep '<string>' | awk -F'[><]' '{print $3}')" >> $GITHUB_ENV

      - name: Install Dependencies
        run: brew install dpkg

      - name: Install cyan and tbd
        run: |
          pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip
          wget --quiet --no-verbose "https://github.com/inoahdev/tbd/releases/download/2.2/tbd-mac" -O /usr/local/bin/tbd
          chmod +x /usr/local/bin/tbd

      - name: Clone and Build YTLite
        run: |
          git clone --quiet --depth=1 https://github.com/SUB2-8687/YTL.git
          cd YTL
          echo "YTL_VERSION=$(grep '^Version:' DEBIAN/control | awk '{print $2}')" >> $GITHUB_ENV
          chmod -R 755 .
          dpkg-deb --root-owner-group -Zgzip --build . ../ytlite.deb
          mv ../ytlite.deb ${{ github.workspace }}/ytlite.deb

      - name: Inject YTLite Into IPA
        run: |
          cyan -i youtube.ipa -o YouTubePlus_${{ env.YT_VERSION }}_${{ env.YTL_VERSION }}.ipa -uwef ytlite.deb -n "${{ inputs.display_name }}" -b ${{ inputs.bundle_id }}

      - name: Create a Draft Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ytl-ipa${{ github.run_number }}
          name: YouTubePlus_${{ env.YT_VERSION }}_${{ env.YTL_VERSION }} (${{ github.run_number }})
          files: YouTubePlus_${{ env.YT_VERSION }}_${{ env.YTL_VERSION }}.ipa
          draft: true

      - name: Job Summary - Build Complete
        run: echo -e '### 🛠️ Build YTLite IPA Complete!' >> $GITHUB_STEP_SUMMARY

      - name: Job Summary - Output the Draft Release Link
        run: |
          echo -e "### 🚀 Draft Release\n\nDraft release has been created successfully! You can view your release here: https://github.com/${{ github.repository }}/releases" >> $GITHUB_STEP_SUMMARY

      - name: Job Summary - Cleanup
        run: |
          echo -e "### 🧹 Cleanup\n\nYou can remove previous GitHub Actions run here: https://github.com/${{ github.repository }}/actions/workflows/delete-old-workflows-run.yml And if you want to delete old draft releases you have then here: https://github.com/${{ github.repository }}/actions/workflows/delete-old-draft-releases.yml" >> $GITHUB_STEP_SUMMARY
